### ISSUE TITLE
Periodically unable to login

### ISSUE THREAD

**Issue by trevore** [oculusinfo/TellFinder#11] opened 2015-02-09 21:12 UTC
Sometimes, seemingly randomly tellfinder stops letting people login. This is the error message.

"HTTP Status 408 - The time allowed for the login process has been exceeded. If you wish to continue you must either click back twice and re-click the link you requested or close and re-open your browser."

That error message comes up almost immediately after entering the credentials so I don't understand the timeout. 

I also want to note that this happens when tellfinder is first starting. However after about 60 seconds it resolves and you can login. I just attributed that to the start up process. 

Today however tellfinder has been running since Friday and it happened first thing this morning as well as in the middle of the afternoon. Restarting tellfinder resolved the issue this afternoon.

**Comment by eric-oculus** [comment] 2015-02-10 18:54
Error code 408 is generated by slow response time during login. See:
   http://www.checkupdown.com/status/E408.html
This error will result from:
  1) Excessive load on the server
  2) Issues with client->server communication times (i.e. slow client internet)

**Comment by trevore** [comment] 2015-02-10 18:59
The server load is 0.01, the RDS instance is at < 10% usage, it happens in
many different locations at the same time, most of which are on very fast
internet connections.

I've also noticed it happens almost instantly. Definitely less then a
second from hitting submit. I wonder if there is a timeout we can change
somewhere?

--Trevor

___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

**Comment by eric-oculus** [comment] 2015-02-13 21:21
Hopefully this is resolved with the latest build using SHIRO authentication.

**Comment by trevore** [comment] 2015-02-13 22:26
Partially. I'm experiences two new strange behaviors.

1. When I login now I'm not redirected to the overview page. It just stays on the https://tellfinder.istresearch.com:8443/tellfinder/TellFinderLogin.html page. If I then go to https://tellfinder.istresearch.com:8443/tellfinder/ it works.

2. When I logout and then go back to the https://tellfinder.istresearch.com:8443/tellfinder/ it does not present me with a login page. On chrome it just gives me a blank page. On Firefox it loads the application (You can see the map) but no data loads.

**Comment by trevore** [comment] 2015-02-13 22:38
An update. It appears that sometimes logout just does not log a user out at all. I'm trying to figure out how to reliably duplicate.

**Comment by dschroh** [comment] 2015-02-13 22:40
Can you test this outside your ELB. I can't make it failing guan. Can you?

On Friday, February 13, 2015, Trevor Ellermann <notifications@github.com>
wrote:

> An update. It appears that sometimes logout just does not log a user out
> at all. I'm trying to figure out how to reliably duplicate.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/oculusinfo/TellFinder/issues/11#issuecomment-74339753>
> .
>


--

**Comment by trevore** [comment] 2015-02-13 22:46
I just used this URL to login. 

http://guan.istresearch.com:8080/tellfinder/
I was redirected back to login so I revisited the above URL.
Once in I just clicked logout, and it brought me to a logout page. I again visited the above URL.
It's now displaying the ui with no data and the "Fetching overview data. Please wait..." message.

Other people are getting a fully functioning UI after logging out using the exact above method. This is happening both on the ELB and talking directly to Guan over http with the above URL.

**Comment by dschroh** [comment] 2015-02-13 23:10
Back my laptop, I'm seeing both issues.  Will spend some time on it this evening and let you know.

**Comment by trevore** [comment] 2015-02-13 23:22
Cool, thanks.

--T

___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

**Comment by dschroh** [comment] 2015-02-14 02:53
The logout is working, but the browser is caching our HTML and so lets you return to the Overview page.  Subsequent data calls fail because you aren't logged in.

To fix, I have added a Cache Control Filter that will disable browser caching for HTML pages.  This shouldn't have any performance effects, but will force HTML pages to check for authentication.

I will push a new container shortly.  

I can only reproduce the login issue on the ELB, which makes me think its a cookie config.  Can you check that the ELB is still using session affinity for JSESSIONID?

**Comment by dschroh** [comment] 2015-02-14 03:06
Cache control for logout added to memex/tellfinder:20150213-11a

**Comment by dschroh** [comment] 2015-02-15 03:24
Confirmed that Shiro doesn't work behind a load balancer without an extra distributed persistence system like memcached or terracotta.  While we look at alternatives, please ensure only a single instance of TellFinder is running behind your ELB.

Pushed a new container (20150214) that still uses Shiro (should fix the 408 and logout issues).  New container removes the need for an external shiro.ini file.  You can delete that file and remove the -v line (the file now reads the environment variables).

**Comment by trevore** [comment] 2015-02-15 08:14
Copy, just one instance behind the load balancer.

I just tried the 20150214 container and I was completely unable to login. I
removed the shiro sed and -v. So this was the line I used to launch the
instance.

docker run -p 8080:8080 -p 8443:8443 -d --name tellfinder-run -e
DATABASE_HOST=roxy-db.istresearch.com -e DATABASE_PORT=3306 -e
DATABASE_USER=oculus -e DATABASE_PASSWORD=removed -e
DATABASE_HT_SCHEMA=memex_ht -e DATABASE_OCULUS_SCHEMA=$@ -e
ELASTICSEARCH_URL=http://74.201.215.27:9200/memex_ht/ad/_search
$TELLFINDER_DOCKER_TAG

So I reverted back to 20150213-11a

___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

**Comment by dschroh** [comment] 2015-02-15 16:56
Hmm.  Not sure what happened there...maybe I pushed the wrong tag?   I just rebuild and tested locally.  Then I spun up a CoreOS stack on AWS and pull this image:

docker pull memex/tellfinder:20150215

Then I ran:

docker run -p 8080:8080 -p 8443:8443 -d --name tellfinder-run -e DATABASE_HOST=roxy-db.istresearch.com -e DATABASE_PORT=3306 -e DATABASE_USER=oculus -e DATABASE_PASSWORD=removed -e DATABASE_HT_SCHEMA=memex_ht -e DATABASE_OCULUS_SCHEMA=memex_uncharted_2 -e ELASTICSEARCH_URL=http://74.201.215.27:9200/memex_ht/ad/_search memex/tellfinder:20150215

The result appears to be running find, HTTP or HTTPS, through an ELB or not:

https://tellfinder-2125710374.us-east-1.elb.amazonaws.com

Login and logout both work well.  No 408 errors.

Due to the limitation I found in Shiro, I'm only running once instance behind the ELB.  I'll be looking at that next week.  We can look at clustering Shiro sessions (ug) or replacing instance authentication with standalone authentication (like WSO2).

**Comment by trevore** [comment] 2015-02-16 10:17
Still not working. To answer an earlier question, affinity is still
enabled.

"Stickiness: AppCookieStickinessPolicy, cookieName='JSESSIONID'"

I wonder if that's actually causing an issue. After I login it changed the
URL to
https://guan.istresearch.com:8443/tellfinder/TellFinderLogin.html;JSESSIONID=3a02177c-3dab-44ec-a473-f29af5ec2f16

So that JSESSIONID is in the URL for some reason. I tried it with affinity
disabled and had no change. I wonder if the ELB was maintaining the old
config for my session or something.

When you tested did you have application affinity turned on the ELB?

Let's not worry about clustering Shiro. One instance is fine and we do plan
to move towards WSO2.

--T

___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

**Comment by dschroh** [comment] 2015-02-16 13:41
I've tried affinity off and on, and Shiro doesn't seem to handle it.  Session affinity worked for Tomcat authentication, which had a single token for your whole session.  Shiro seems to assign you an unauthenticated session token, and then change it during authentication. This seems to screw up the load balancer regardless of how you set it.  Hence, we'll need to move to something like OpenID or SAML SSO.

I'm pretty sure that guan isn't running 20150215, since the logout link doesn't work in yours, but works fine in mine:  https://tellfinder-2125710374.us-east-1.elb.amazonaws.com/tellfinder/

**Comment by trevore** [comment] 2015-02-16 19:48
Correct, I reverted to 20150213-11a when it could not login in case one of
the pilots want to use it today. If you would like to look at it with me I
can put it up. Let's schedule a time?

BTW, I tried authenticating directly, not through the ELB and got the same
result.

___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

**Comment by dschroh** [comment] 2015-02-19 21:50
I have pushed a new container (20150219a) which contains a fix for the final part of this bug.  Sometimes, on Amazon, Shiro returns 200 instead of 302 when you successfully authenticate.

We added some JS (tested on Chrome, FF and IE) that detects if you are authenticated when you load the login page.  If so, you are redirected automatically to the Overview.

**Comment by trevore** [comment] 2015-02-19 21:56
Cool. That worked the first time I went to test it. I however then went to
logout and got a 404 error.

https://tellfinder.istresearch.com:8443/tellfinder/logout

Also, should I be including the -v
/var/lib/tellfinder/shiro.ini:/etc/tellfinder/shiro.ini:ro in the docker
run at this point?

___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

**Comment by dschroh** [comment] 2015-02-19 21:57
No, please don't override the default shiro.ini any longer. The image now ships with a self-contained config.  (That's why logout doesn't work)

**Comment by trevore** [comment] 2015-02-19 22:08
The self-contained config does not work for some reason. If I take out the
-v it does not let me login at all.

I'm comparing the two configs to see if I can find anything obvious.

--T

___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

**Comment by trevore** [comment] 2015-02-19 22:13
Well I don't know why the built in shiro.ini is not working but I added the
below line to the one we are doing in the -v and it works now.

/logout = logout



___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

**Comment by dschroh** [comment] 2015-02-19 22:17
OK.  I'll mark this resolved.

I'll want to pick your brain about that later.  I've pushed that same built to two different fresh Amazon instances and they worked against different fresh RDS instances, so you shouldn't need the shiro.ini file.  But if that config is stable, and can get us through to the point where we have OpenID implemented, then we're good.

**Closed by dschroh** 2015-02-19 22:17 UTC
